include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: 'main'
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  OPT_IN_TEST_NEXT_MAJOR: '1'
  OPT_IN_TEST_NEXT_MINOR: '1'
  OPT_IN_TEST_PREVIOUS_MINOR: '1'
  RUN_JOB_UPGRADE_STATUS: '1'
  _CURL_TEMPLATES_REF: 'main'

