http_cache_control.settings:
  type: config_object
  label: 'HTTP Cache-Control Settings'
  mapping:
    cache:
      type: mapping
      label: 'Cache Control'
      mapping:
        http:
          type: mapping
          label: 'Page caching'
          mapping:
            s_maxage:
              type: integer
              label: 'Shared cache max age'
            404_max_age:
              type: integer
              label: '404 max age'
            302_max_age:
              type: integer
              label: '302 max age'
            301_max_age:
              type: integer
              label: '301 max age'
            5xx_max_age:
              type: integer
              label: '5xx max age'
            stale_while_revalidate:
              type: integer
              label: 'Stale while revalidate'
            stale_if_error:
              type: integer
              label: 'Stale if error'
            vary:
              type: string
              label: 'Vary'
            mustrevalidate:
              type: boolean
              label: 'Cache-Control: must-revalidate'
            nocache:
              type: boolean
              label: 'Cache-Control: no-cache'
            nostore:
              type: boolean
              label: 'Cache-Control: no-store'
        surrogate:
          type: mapping
          label: 'Surrogate-Control'
          mapping:
            maxage:
              type: integer
              label: 'Surrogate max age'
            nostore:
              type: boolean
              label: 'Surrogate no-store'
